databases:
  - name: question-bank
    plan: free
    databaseName: questiondb_3yd3
    user: questiondb_3yd3_user

services:
  - type: web
    plan: free
    name: ai_question_generator
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn ai_question_generator.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  questiondb_3yd3
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4